import Navbar from "@/components/ui/navbar";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body>
        <main className="flex flex-col items-center center w-full p-8 min-h-screen">
          <Navbar />
          <div className="flex flex-col gap-8 h-full w-full max-w-5xl">
            <div className={inter.className}>{children}</div>
          </div>
        </main>
      </body>
    </html>
  );
}
